shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
+  exception:
+    security: false

default:
  index:
    security: true
    credentials:
      - [admin, cajero]
  insert:
    security: true
 ##-----------ANIMAL--------------------##   
animal:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##---------- CIUDAD ---------------------##
ciudad:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##---------- CREDENCIAL -----------------##
credencial:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##---------- DETALLE ENTRADA ------------##
detalle_entrada:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
  view:
    security: true
    credentials:
      - [admin]
##---------- ENTRADA BODEGA -------------##
entrada_bodega:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##---------- ESTADO ---------------------##
estado:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##---------- FECUNDADOR -----------------##
fecundador:
  index:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]

##--------- Insumo -----------------------##
insumo:
  index:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##--------- INVENTARIO -------------------##
##--------- ORDEÑO -----------------------##
ordenno:
  index:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##--------- PAGO TRABAJADORES ------------##
##--------- PROVEEDOR --------------------##
proveedor:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
##--------- RAZA -------------------------##
raza:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##--------- REGISTRO CELO ----------------##      
registro_celo:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
##----------REGISTRO VACUNACION --------##
registro_vacunacion:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##----------REPORTE PARTO --------------##
##---------- SALIDA BODEGA -------------##
##---------- TIPO INSUMO ---------------##
tipo_insumo:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
#-----------Trabajador -------------------
trabajador:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
#----------- Turno -----------------
turno:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
  create:
    security: true
    credentials:
      - [admin]
  edit:
    security: true
    credentials:
      - [admin]
  update:
    security: true
    credentials:
      - [admin]
  delete:
    security: true
    credentials:
      - [admin]
  deleteSelect:
    security: true
    credentials:
      - [admin]
##------------ USUARIO --------------##
##------------ USUARIO CREDENCIAL ---##