shfSecurity:
  index:
    security: false
  login:
    security: false
  logout:
    security: true
  noPermission:
    security: false
+  exception:
+    security: false

default:
  index:
    security: true
    credentials:
      - [admin, cajero]
  insert:
    security: true
    
animal:
  index:
    security: true
    credentials:
      - [admin]
  insert:
    security: true
    credentials:
      - [admin]
