shfSecurity:
  index:
    security: false
  logoin:
    security: false
  logout:
    security: true
  noPermission:
    security: false
+  exception:
+    security: false

default:
  index:
    security: true
    credentials:
      - [admin, cajero]
  insert:
    security: true
