all:
  favicon: hola.ico
  title: Corral de Piedras
  meta:
    - charset="UTF-8"
    - http-equiv="X-UA-Compatible" content="IE=edge"
  javascript:
    - jquery-1.11.1.min.js
    - bootstrap.js
    - main.js
  stylesheet:
    - bootstrap.css
    - main.css
    - font-awesome.min.css
    
shfSecurity:
  index:
    title: Identificacion de usuario
    stylesheet:
      - signin.css
     # - modern-business.css

#default:
#  index:
#  title: Corral de Piedras
#  meta:
#    - charset="UTF-8"
#    - http-equiv="X-UA-Compatible" content="IE=edge"
#    - name="viewport" content="width=device-width, initial-scale=1"
#  javascript:
#    - jquery-1.11.1.min.js
#    - bootstrap.js
#    - main.js
#  stylesheet:
#    - bootstrap.css
#    - main.css
#    - font-awesome.min.css
#    - modern-business.css
#--------------- Animal -------------------------
animal:
  index:
    javascript:
      - index.js
  stylesheet:
      - main.css
#--------------- Bitacora -------------------------
#--------------- Ciudad -------------------------
ciudad:
  index:
    javascript:
      - index.js
  stylesheet:
      - main.css
#--------------- Credencial -------------------------
credencial:
  index:
    javascript:
      - index.js
#--------------- Detalle Entrada -----------------------
detalle_entrada:
  index:
    javascript:
      - index.js
#--------------- Entrada Bodega -------------------------
entrada_bodega:
  index:
    javascript:
      - index.js
#--------------- Estado -------------------------
estado:
  index:
    javascript:
      - index.js
#--------------- Fecundador -------------------------
fecundador:
  index:
    javascript:
      - index.js
#--------------- Insumo -------------------------
insumo:
  index:
    javascript:
      - index.js
#--------------- Inventario -------------------------
#--------------- Ordeño -------------------------
ordenno:
  index:
    javascript:
      - index.js
  grafica:
    javascript:
      - jqPlot/jquery.jqplot.min.js
      - jqPlot/plugins/jqplot.canvasTextRenderer.min.js
      - jqPlot/plugins/jqplot.canvasAxisTickRenderer.min.js
      - grafica.js
  stylesheet:
    - jquery.jqplot.min.css
#--------------- Pago Trabajadores -------------------------
#--------------- Proveedor -------------------------
proveedor:
  index:
    javascript:
      - index.js
#--------------- Raza -------------------------
raza:
  index:
    javascript:
      - index.js
#--------------- Registro Celo -------------------------
registro_celo:
  index:
    javascript:
      - index.js
#--------------- Registro Vacunacion -------------------------
registro_vacunacion:
  index:
    javascript:
      - index.js
#--------------- Salida Bodega -------------------------
#--------------- Tipo Insumo -------------------------
tipo_insumo:
  index:
    javascript:
      - index.js
#--------------- Trabajador -------------------------
trabajador:
  index:
    javascript:
      - index.js
#--------------- Turno ------------------------
turno:
  index:
    javascript:
      - index.js
