all:
  favicon: hola.ico
  title: Corral de Piedras
  meta:
    - charset="UTF-8"
  javascript:
    - jquery-1.11.1.min.js
    - bootstrap.js
    - main.js
  stylesheet:
    - bootstrap.css
    - main.css
    - font-awesome.min.css

shfSecurity:
  index:
    title: Identificacion de usuario
    stylesheet:
      - signin.css

default:
  index:
    javascript:
      - index.js

animal:
  index:
    javascript:
      - index.js
      
fecundador:
  index:
    javascript:
      - index.js

raza:
  index:
    javascript:
      - index.js
      
registro_celo:
  index:
    javascript:
      - index.js
