--
-- PostgreSQL database dump
--

-- Dumped from database version 9.4.0
-- Dumped by pg_dump version 9.4.0
-- Started on 2015-04-21 13:33:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

--
-- TOC entry 229 (class 3079 OID 11855)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2357 (class 0 OID 0)
-- Dependencies: 229
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET search_path = public, pg_catalog;

--
-- TOC entry 172 (class 1259 OID 34751)
-- Name: animal_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "animal_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "animal_Id_seq" OWNER TO postgres;

--
-- TOC entry 2358 (class 0 OID 0)
-- Dependencies: 172
-- Name: SEQUENCE "animal_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "animal_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 173 (class 1259 OID 34753)
-- Name: bitacora_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE bitacora_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE bitacora_id_seq OWNER TO postgres;

--
-- TOC entry 2359 (class 0 OID 0)
-- Dependencies: 173
-- Name: SEQUENCE bitacora_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 201 (class 1259 OID 34809)
-- Name: bitacora; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE bitacora (
    id bigint DEFAULT nextval('bitacora_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    accion character varying(80) NOT NULL,
    tabla character varying(80) NOT NULL,
    registro bigint,
    observacion character varying(1024),
    fecha timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE bitacora OWNER TO postgres;

--
-- TOC entry 174 (class 1259 OID 34755)
-- Name: cargo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "cargo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "cargo_Id_seq" OWNER TO postgres;

--
-- TOC entry 2360 (class 0 OID 0)
-- Dependencies: 174
-- Name: SEQUENCE "cargo_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "cargo_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 175 (class 1259 OID 34757)
-- Name: ciudad_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "ciudad_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "ciudad_Id_seq" OWNER TO postgres;

--
-- TOC entry 2361 (class 0 OID 0)
-- Dependencies: 175
-- Name: SEQUENCE "ciudad_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "ciudad_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 202 (class 1259 OID 34821)
-- Name: ciudad; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE ciudad (
    id integer DEFAULT nextval('"ciudad_Id_seq"'::regclass) NOT NULL,
    descripcion character varying(140) NOT NULL
);


ALTER TABLE ciudad OWNER TO postgres;

--
-- TOC entry 176 (class 1259 OID 34759)
-- Name: credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2362 (class 0 OID 0)
-- Dependencies: 176
-- Name: SEQUENCE credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 203 (class 1259 OID 34827)
-- Name: credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE credencial (
    id bigint DEFAULT nextval('credencial_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE credencial OWNER TO postgres;

--
-- TOC entry 177 (class 1259 OID 34761)
-- Name: detalle_entrada_bodega_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_entrada_bodega_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_entrada_bodega_Id_seq" OWNER TO postgres;

--
-- TOC entry 2363 (class 0 OID 0)
-- Dependencies: 177
-- Name: SEQUENCE "detalle_entrada_bodega_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_entrada_bodega_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 204 (class 1259 OID 34835)
-- Name: detalle_entrada_bodega; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_entrada_bodega (
    id integer DEFAULT nextval('"detalle_entrada_bodega_Id_seq"'::regclass) NOT NULL,
    cantidad integer NOT NULL,
    valor integer NOT NULL,
    id_entrada_bodega integer NOT NULL,
    id_insumo integer NOT NULL
);


ALTER TABLE detalle_entrada_bodega OWNER TO postgres;

--
-- TOC entry 178 (class 1259 OID 34763)
-- Name: detalle_pago_trabajador_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE "detalle_pago_trabajador_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "detalle_pago_trabajador_Id_seq" OWNER TO postgres;

--
-- TOC entry 2364 (class 0 OID 0)
-- Dependencies: 178
-- Name: SEQUENCE "detalle_pago_trabajador_Id_seq"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE "detalle_pago_trabajador_Id_seq" IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 205 (class 1259 OID 34841)
-- Name: detalle_pago_trabajadores; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_pago_trabajadores (
    id integer DEFAULT nextval('"detalle_pago_trabajador_Id_seq"'::regclass) NOT NULL,
    salario integer NOT NULL,
    horas_extras integer NOT NULL,
    cantidad_dias integer NOT NULL,
    id_pago_trabajador integer NOT NULL
);


ALTER TABLE detalle_pago_trabajadores OWNER TO postgres;

--
-- TOC entry 179 (class 1259 OID 34765)
-- Name: detalle_registro_vacunacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE detalle_registro_vacunacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE detalle_registro_vacunacion_id_seq OWNER TO postgres;

--
-- TOC entry 2365 (class 0 OID 0)
-- Dependencies: 179
-- Name: SEQUENCE detalle_registro_vacunacion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE detalle_registro_vacunacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 206 (class 1259 OID 34847)
-- Name: detalle_registro_vacunacion; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_registro_vacunacion (
    id integer DEFAULT nextval('detalle_registro_vacunacion_id_seq'::regclass) NOT NULL,
    dosis_vacuna character varying(30) NOT NULL,
    hora_vacuna time without time zone NOT NULL,
    id_registro_vacunacion integer NOT NULL,
    id_animal integer NOT NULL,
    id_insumo integer NOT NULL
);


ALTER TABLE detalle_registro_vacunacion OWNER TO postgres;

--
-- TOC entry 180 (class 1259 OID 34767)
-- Name: detalle_salida_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE detalle_salida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE detalle_salida_id_seq OWNER TO postgres;

--
-- TOC entry 2366 (class 0 OID 0)
-- Dependencies: 180
-- Name: SEQUENCE detalle_salida_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE detalle_salida_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 207 (class 1259 OID 34853)
-- Name: detalle_salida; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE detalle_salida (
    id integer DEFAULT nextval('detalle_salida_id_seq'::regclass) NOT NULL,
    cantidad character varying(8) NOT NULL,
    id_salida_bodega integer NOT NULL,
    id_insumo integer NOT NULL,
    id_tipo_insumo integer NOT NULL
);


ALTER TABLE detalle_salida OWNER TO postgres;

--
-- TOC entry 181 (class 1259 OID 34769)
-- Name: entrada_bodega_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE entrada_bodega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE entrada_bodega_id_seq OWNER TO postgres;

--
-- TOC entry 2367 (class 0 OID 0)
-- Dependencies: 181
-- Name: SEQUENCE entrada_bodega_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE entrada_bodega_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 208 (class 1259 OID 34859)
-- Name: entrada_bodega; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE entrada_bodega (
    id integer DEFAULT nextval('entrada_bodega_id_seq'::regclass) NOT NULL,
    fecha date NOT NULL,
    hora time without time zone NOT NULL,
    id_tipo_doc integer NOT NULL,
    id_trabajador integer NOT NULL,
    id_proveedor integer NOT NULL
);


ALTER TABLE entrada_bodega OWNER TO postgres;

--
-- TOC entry 182 (class 1259 OID 34771)
-- Name: estado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE estado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE estado_id_seq OWNER TO postgres;

--
-- TOC entry 2368 (class 0 OID 0)
-- Dependencies: 182
-- Name: SEQUENCE estado_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE estado_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 209 (class 1259 OID 34865)
-- Name: estado; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE estado (
    id integer DEFAULT nextval('estado_id_seq'::regclass) NOT NULL,
    descripcion character varying(140) NOT NULL
);


ALTER TABLE estado OWNER TO postgres;

--
-- TOC entry 183 (class 1259 OID 34773)
-- Name: fecundador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE fecundador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE fecundador_id_seq OWNER TO postgres;

--
-- TOC entry 2369 (class 0 OID 0)
-- Dependencies: 183
-- Name: SEQUENCE fecundador_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE fecundador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 210 (class 1259 OID 34871)
-- Name: fecundador; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE fecundador (
    id integer DEFAULT nextval('fecundador_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    edad integer NOT NULL,
    peso integer NOT NULL,
    observacion character varying(150) NOT NULL,
    id_raza integer NOT NULL
);


ALTER TABLE fecundador OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 34877)
-- Name: hoja_de_vida; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE hoja_de_vida (
    id integer DEFAULT nextval('"animal_Id_seq"'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    genero character(1) NOT NULL,
    edad integer NOT NULL,
    peso integer NOT NULL,
    fecha_ingreso date NOT NULL,
    numero_partos integer NOT NULL,
    id_raza integer NOT NULL,
    id_estado integer NOT NULL
);


ALTER TABLE hoja_de_vida OWNER TO postgres;

--
-- TOC entry 184 (class 1259 OID 34775)
-- Name: insumo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE insumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE insumo_id_seq OWNER TO postgres;

--
-- TOC entry 2370 (class 0 OID 0)
-- Dependencies: 184
-- Name: SEQUENCE insumo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE insumo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 212 (class 1259 OID 34883)
-- Name: insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE insumo (
    id integer DEFAULT nextval('insumo_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    fecha_fabrica date NOT NULL,
    fecha_vencimiento date NOT NULL,
    valor integer NOT NULL,
    id_tipo_insumo integer NOT NULL
);


ALTER TABLE insumo OWNER TO postgres;

--
-- TOC entry 185 (class 1259 OID 34777)
-- Name: inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE inventario_id_seq OWNER TO postgres;

--
-- TOC entry 2371 (class 0 OID 0)
-- Dependencies: 185
-- Name: SEQUENCE inventario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE inventario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 213 (class 1259 OID 34889)
-- Name: inventario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE inventario (
    id integer DEFAULT nextval('inventario_id_seq'::regclass) NOT NULL,
    fecha date NOT NULL,
    cantidad character varying(3) NOT NULL,
    valor integer NOT NULL,
    saldo integer NOT NULL,
    id_animal integer NOT NULL,
    id_tipo_doc integer NOT NULL,
    id_insumo integer NOT NULL
);


ALTER TABLE inventario OWNER TO postgres;

--
-- TOC entry 186 (class 1259 OID 34779)
-- Name: ordeno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE ordeno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE ordeno_id_seq OWNER TO postgres;

--
-- TOC entry 2372 (class 0 OID 0)
-- Dependencies: 186
-- Name: SEQUENCE ordeno_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE ordeno_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 214 (class 1259 OID 34895)
-- Name: ordeno; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE ordeno (
    id integer DEFAULT nextval('ordeno_id_seq'::regclass) NOT NULL,
    fecha_ordeno date NOT NULL,
    cantidad_leche integer NOT NULL,
    id_trabajador integer NOT NULL,
    id_animal integer NOT NULL
);


ALTER TABLE ordeno OWNER TO postgres;

--
-- TOC entry 187 (class 1259 OID 34781)
-- Name: pago_trabajadores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE pago_trabajadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE pago_trabajadores_id_seq OWNER TO postgres;

--
-- TOC entry 2373 (class 0 OID 0)
-- Dependencies: 187
-- Name: SEQUENCE pago_trabajadores_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE pago_trabajadores_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 215 (class 1259 OID 34901)
-- Name: pago_trabajadores; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE pago_trabajadores (
    id integer DEFAULT nextval('pago_trabajadores_id_seq'::regclass) NOT NULL,
    fecha_inicio character varying(10) NOT NULL,
    fecha_fin character varying(10) NOT NULL,
    subtotal integer NOT NULL,
    valor_hora integer NOT NULL,
    id_trabajador integer NOT NULL
);


ALTER TABLE pago_trabajadores OWNER TO postgres;

--
-- TOC entry 188 (class 1259 OID 34783)
-- Name: proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE proveedor_id_seq OWNER TO postgres;

--
-- TOC entry 2374 (class 0 OID 0)
-- Dependencies: 188
-- Name: SEQUENCE proveedor_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE proveedor_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 216 (class 1259 OID 34907)
-- Name: proveedor; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE proveedor (
    id integer DEFAULT nextval('proveedor_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    apellido character varying(80) NOT NULL,
    direccion character varying(120) NOT NULL,
    telefono integer NOT NULL,
    correo character varying(120) NOT NULL,
    id_ciudad integer NOT NULL
);


ALTER TABLE proveedor OWNER TO postgres;

--
-- TOC entry 189 (class 1259 OID 34785)
-- Name: raza_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE raza_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE raza_id_seq OWNER TO postgres;

--
-- TOC entry 2375 (class 0 OID 0)
-- Dependencies: 189
-- Name: SEQUENCE raza_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE raza_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 217 (class 1259 OID 34913)
-- Name: raza; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE raza (
    id integer DEFAULT nextval('raza_id_seq'::regclass) NOT NULL,
    descripcion character varying(140) NOT NULL
);


ALTER TABLE raza OWNER TO postgres;

--
-- TOC entry 190 (class 1259 OID 34787)
-- Name: recordar_me_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE recordar_me_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE recordar_me_id_seq OWNER TO postgres;

--
-- TOC entry 2376 (class 0 OID 0)
-- Dependencies: 190
-- Name: SEQUENCE recordar_me_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 218 (class 1259 OID 34919)
-- Name: recordar_me; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recordar_me (
    id bigint DEFAULT nextval('recordar_me_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    ip_address character varying(50) NOT NULL,
    hash_cookie character varying(32) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE recordar_me OWNER TO postgres;

--
-- TOC entry 191 (class 1259 OID 34789)
-- Name: registro_celo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE registro_celo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE registro_celo_id_seq OWNER TO postgres;

--
-- TOC entry 2377 (class 0 OID 0)
-- Dependencies: 191
-- Name: SEQUENCE registro_celo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE registro_celo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 219 (class 1259 OID 34928)
-- Name: registro_celo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE registro_celo (
    id integer DEFAULT nextval('registro_celo_id_seq'::regclass) NOT NULL,
    edad_animal integer NOT NULL,
    fecha date NOT NULL,
    id_fecundador integer NOT NULL,
    id_animal integer NOT NULL
);


ALTER TABLE registro_celo OWNER TO postgres;

--
-- TOC entry 192 (class 1259 OID 34791)
-- Name: registro_vacunacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE registro_vacunacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE registro_vacunacion_id_seq OWNER TO postgres;

--
-- TOC entry 2378 (class 0 OID 0)
-- Dependencies: 192
-- Name: SEQUENCE registro_vacunacion_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE registro_vacunacion_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 220 (class 1259 OID 34934)
-- Name: registro_vacunacion; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE registro_vacunacion (
    id integer DEFAULT nextval('registro_vacunacion_id_seq'::regclass) NOT NULL,
    fecha_registro date NOT NULL,
    id_trabajador integer NOT NULL
);


ALTER TABLE registro_vacunacion OWNER TO postgres;

--
-- TOC entry 193 (class 1259 OID 34793)
-- Name: reporte_parto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE reporte_parto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE reporte_parto_id_seq OWNER TO postgres;

--
-- TOC entry 2379 (class 0 OID 0)
-- Dependencies: 193
-- Name: SEQUENCE reporte_parto_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE reporte_parto_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 221 (class 1259 OID 34940)
-- Name: reporte_parto; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE reporte_parto (
    id integer DEFAULT nextval('reporte_parto_id_seq'::regclass) NOT NULL,
    fecha_parto date NOT NULL,
    n_animales_vi integer NOT NULL,
    n_animales_m integer NOT NULL,
    n_machos integer NOT NULL,
    n_hembras integer NOT NULL,
    observaciones character varying(150) NOT NULL,
    id_animal integer NOT NULL
);


ALTER TABLE reporte_parto OWNER TO postgres;

--
-- TOC entry 194 (class 1259 OID 34795)
-- Name: salida_bodega_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE salida_bodega_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE salida_bodega_id_seq OWNER TO postgres;

--
-- TOC entry 2380 (class 0 OID 0)
-- Dependencies: 194
-- Name: SEQUENCE salida_bodega_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE salida_bodega_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 222 (class 1259 OID 34946)
-- Name: salida_bodega; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE salida_bodega (
    id integer DEFAULT nextval('salida_bodega_id_seq'::regclass) NOT NULL,
    fecha date NOT NULL,
    id_tipo_doc integer NOT NULL,
    id_trabajador integer NOT NULL
);


ALTER TABLE salida_bodega OWNER TO postgres;

--
-- TOC entry 195 (class 1259 OID 34797)
-- Name: tipo_documento_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_documento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tipo_documento_id_seq OWNER TO postgres;

--
-- TOC entry 2381 (class 0 OID 0)
-- Dependencies: 195
-- Name: SEQUENCE tipo_documento_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_documento_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 223 (class 1259 OID 34952)
-- Name: tipo_documento; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_documento (
    id integer DEFAULT nextval('tipo_documento_id_seq'::regclass) NOT NULL,
    descripcion character varying(140) NOT NULL,
    movimiento character varying(10) NOT NULL
);


ALTER TABLE tipo_documento OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 34799)
-- Name: tipo_insumo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE tipo_insumo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE tipo_insumo_id_seq OWNER TO postgres;

--
-- TOC entry 2382 (class 0 OID 0)
-- Dependencies: 196
-- Name: SEQUENCE tipo_insumo_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE tipo_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 224 (class 1259 OID 34958)
-- Name: tipo_insumo; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE tipo_insumo (
    id integer DEFAULT nextval('tipo_insumo_id_seq'::regclass) NOT NULL,
    descripcion character varying(140) NOT NULL
);


ALTER TABLE tipo_insumo OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 34801)
-- Name: trabajador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE trabajador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE trabajador_id_seq OWNER TO postgres;

--
-- TOC entry 2383 (class 0 OID 0)
-- Dependencies: 197
-- Name: SEQUENCE trabajador_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE trabajador_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 225 (class 1259 OID 34964)
-- Name: trabajador; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE trabajador (
    id integer DEFAULT nextval('trabajador_id_seq'::regclass) NOT NULL,
    nombre character varying(80) NOT NULL,
    apellido character varying(80) NOT NULL,
    direccion character varying(120) NOT NULL,
    telefono integer NOT NULL,
    id_turno integer NOT NULL,
    id_credencial integer NOT NULL,
    id_ciudad integer NOT NULL
);


ALTER TABLE trabajador OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 34803)
-- Name: turno_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE turno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE turno_id_seq OWNER TO postgres;

--
-- TOC entry 2384 (class 0 OID 0)
-- Dependencies: 198
-- Name: SEQUENCE turno_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE turno_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 226 (class 1259 OID 34970)
-- Name: turno; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE turno (
    id integer DEFAULT nextval('turno_id_seq'::regclass) NOT NULL,
    descripcion character varying(140) NOT NULL,
    inicio_turno time without time zone NOT NULL,
    fin_turno time without time zone NOT NULL
);


ALTER TABLE turno OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 34807)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_id_seq OWNER TO postgres;

--
-- TOC entry 2385 (class 0 OID 0)
-- Dependencies: 200
-- Name: SEQUENCE usuario_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 227 (class 1259 OID 34976)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario (
    id bigint DEFAULT nextval('usuario_id_seq'::regclass) NOT NULL,
    user_name character varying(80) NOT NULL,
    password character varying(32) NOT NULL,
    actived boolean DEFAULT true NOT NULL,
    last_login_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE usuario OWNER TO postgres;

--
-- TOC entry 2386 (class 0 OID 0)
-- Dependencies: 227
-- Name: COLUMN usuario.actived; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';


--
-- TOC entry 199 (class 1259 OID 34805)
-- Name: usuario_credencial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE usuario_credencial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE usuario_credencial_id_seq OWNER TO postgres;

--
-- TOC entry 2387 (class 0 OID 0)
-- Dependencies: 199
-- Name: SEQUENCE usuario_credencial_id_seq; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';


--
-- TOC entry 228 (class 1259 OID 34989)
-- Name: usuario_credencial; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE usuario_credencial (
    id bigint DEFAULT nextval('usuario_credencial_id_seq'::regclass) NOT NULL,
    usuario_id bigint NOT NULL,
    credencial_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE usuario_credencial OWNER TO postgres;

--
-- TOC entry 2388 (class 0 OID 0)
-- Dependencies: 172
-- Name: animal_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"animal_Id_seq"', 2, true);


--
-- TOC entry 2323 (class 0 OID 34809)
-- Dependencies: 201
-- Data for Name: bitacora; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (1, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 19:29:40');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (2, 1, 'Insertar', 'hoja_de_vida', NULL, NULL, '2015-04-20 19:36:32');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (3, 1, 'Actualizar', 'hoja_de_vida', NULL, NULL, '2015-04-20 19:36:48');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (4, 1, 'Insertar', 'hoja_de_vida', NULL, NULL, '2015-04-20 19:39:25');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (5, 1, 'Eliminar Individual', 'hoja_de_vida', NULL, NULL, '2015-04-20 19:39:50');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (6, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 21:30:44');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (7, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 23:29:03');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (8, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-20 23:31:55');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (9, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 05:04:34');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (10, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 15:40:09');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (11, 1, 'INSERTAR', 'fecundador', NULL, NULL, '2015-04-21 18:48:54');
INSERT INTO bitacora (id, usuario_id, accion, tabla, registro, observacion, fecha) VALUES (12, 1, 'identificación', 'NINGUNA', NULL, NULL, '2015-04-21 20:16:26');


--
-- TOC entry 2389 (class 0 OID 0)
-- Dependencies: 173
-- Name: bitacora_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('bitacora_id_seq', 12, true);


--
-- TOC entry 2390 (class 0 OID 0)
-- Dependencies: 174
-- Name: cargo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"cargo_Id_seq"', 1, false);


--
-- TOC entry 2324 (class 0 OID 34821)
-- Dependencies: 202
-- Data for Name: ciudad; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2391 (class 0 OID 0)
-- Dependencies: 175
-- Name: ciudad_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"ciudad_Id_seq"', 1, false);


--
-- TOC entry 2325 (class 0 OID 34827)
-- Dependencies: 203
-- Data for Name: credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO credencial (id, nombre, created_at, updated_at, deleted_at) VALUES (1, 'admin', '2015-04-20 12:28:22.287', '2015-04-20 12:28:22.287', NULL);
INSERT INTO credencial (id, nombre, created_at, updated_at, deleted_at) VALUES (2, 'usuario', '2015-04-20 12:28:22.287', '2015-04-20 12:28:22.287', NULL);


--
-- TOC entry 2392 (class 0 OID 0)
-- Dependencies: 176
-- Name: credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('credencial_id_seq', 2, true);


--
-- TOC entry 2326 (class 0 OID 34835)
-- Dependencies: 204
-- Data for Name: detalle_entrada_bodega; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2393 (class 0 OID 0)
-- Dependencies: 177
-- Name: detalle_entrada_bodega_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_entrada_bodega_Id_seq"', 1, false);


--
-- TOC entry 2394 (class 0 OID 0)
-- Dependencies: 178
-- Name: detalle_pago_trabajador_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"detalle_pago_trabajador_Id_seq"', 1, false);


--
-- TOC entry 2327 (class 0 OID 34841)
-- Dependencies: 205
-- Data for Name: detalle_pago_trabajadores; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2328 (class 0 OID 34847)
-- Dependencies: 206
-- Data for Name: detalle_registro_vacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2395 (class 0 OID 0)
-- Dependencies: 179
-- Name: detalle_registro_vacunacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('detalle_registro_vacunacion_id_seq', 1, false);


--
-- TOC entry 2329 (class 0 OID 34853)
-- Dependencies: 207
-- Data for Name: detalle_salida; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2396 (class 0 OID 0)
-- Dependencies: 180
-- Name: detalle_salida_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('detalle_salida_id_seq', 1, false);


--
-- TOC entry 2330 (class 0 OID 34859)
-- Dependencies: 208
-- Data for Name: entrada_bodega; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2397 (class 0 OID 0)
-- Dependencies: 181
-- Name: entrada_bodega_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('entrada_bodega_id_seq', 1, false);


--
-- TOC entry 2331 (class 0 OID 34865)
-- Dependencies: 209
-- Data for Name: estado; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO estado (id, descripcion) VALUES (1, 'Activo');
INSERT INTO estado (id, descripcion) VALUES (2, 'Inactivo');


--
-- TOC entry 2398 (class 0 OID 0)
-- Dependencies: 182
-- Name: estado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('estado_id_seq', 2, true);


--
-- TOC entry 2332 (class 0 OID 34871)
-- Dependencies: 210
-- Data for Name: fecundador; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO fecundador (id, nombre, edad, peso, observacion, id_raza) VALUES (1, 'pepito', 12, 23, 'Perfecto', 1);
INSERT INTO fecundador (id, nombre, edad, peso, observacion, id_raza) VALUES (2, 'juan manuel', 12, 34, 'Perfecto', 1);
INSERT INTO fecundador (id, nombre, edad, peso, observacion, id_raza) VALUES (3, 'peptio', 12, 34, 'Perfecto', 1);


--
-- TOC entry 2399 (class 0 OID 0)
-- Dependencies: 183
-- Name: fecundador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('fecundador_id_seq', 3, true);


--
-- TOC entry 2333 (class 0 OID 34877)
-- Dependencies: 211
-- Data for Name: hoja_de_vida; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO hoja_de_vida (id, nombre, genero, edad, peso, fecha_ingreso, numero_partos, id_raza, id_estado) VALUES (2, 'animal', 'F', 12, 12, '2015-04-17', 1, 1, 1);


--
-- TOC entry 2334 (class 0 OID 34883)
-- Dependencies: 212
-- Data for Name: insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2400 (class 0 OID 0)
-- Dependencies: 184
-- Name: insumo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('insumo_id_seq', 1, false);


--
-- TOC entry 2335 (class 0 OID 34889)
-- Dependencies: 213
-- Data for Name: inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2401 (class 0 OID 0)
-- Dependencies: 185
-- Name: inventario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('inventario_id_seq', 1, false);


--
-- TOC entry 2336 (class 0 OID 34895)
-- Dependencies: 214
-- Data for Name: ordeno; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2402 (class 0 OID 0)
-- Dependencies: 186
-- Name: ordeno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('ordeno_id_seq', 1, false);


--
-- TOC entry 2337 (class 0 OID 34901)
-- Dependencies: 215
-- Data for Name: pago_trabajadores; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2403 (class 0 OID 0)
-- Dependencies: 187
-- Name: pago_trabajadores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('pago_trabajadores_id_seq', 1, false);


--
-- TOC entry 2338 (class 0 OID 34907)
-- Dependencies: 216
-- Data for Name: proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2404 (class 0 OID 0)
-- Dependencies: 188
-- Name: proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('proveedor_id_seq', 1, false);


--
-- TOC entry 2339 (class 0 OID 34913)
-- Dependencies: 217
-- Data for Name: raza; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO raza (id, descripcion) VALUES (1, 'Ojos Rojos');


--
-- TOC entry 2405 (class 0 OID 0)
-- Dependencies: 189
-- Name: raza_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('raza_id_seq', 1, true);


--
-- TOC entry 2340 (class 0 OID 34919)
-- Dependencies: 218
-- Data for Name: recordar_me; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2406 (class 0 OID 0)
-- Dependencies: 190
-- Name: recordar_me_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('recordar_me_id_seq', 1, false);


--
-- TOC entry 2341 (class 0 OID 34928)
-- Dependencies: 219
-- Data for Name: registro_celo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2407 (class 0 OID 0)
-- Dependencies: 191
-- Name: registro_celo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('registro_celo_id_seq', 1, false);


--
-- TOC entry 2342 (class 0 OID 34934)
-- Dependencies: 220
-- Data for Name: registro_vacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2408 (class 0 OID 0)
-- Dependencies: 192
-- Name: registro_vacunacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('registro_vacunacion_id_seq', 1, false);


--
-- TOC entry 2343 (class 0 OID 34940)
-- Dependencies: 221
-- Data for Name: reporte_parto; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2409 (class 0 OID 0)
-- Dependencies: 193
-- Name: reporte_parto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('reporte_parto_id_seq', 1, false);


--
-- TOC entry 2344 (class 0 OID 34946)
-- Dependencies: 222
-- Data for Name: salida_bodega; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2410 (class 0 OID 0)
-- Dependencies: 194
-- Name: salida_bodega_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('salida_bodega_id_seq', 1, false);


--
-- TOC entry 2345 (class 0 OID 34952)
-- Dependencies: 223
-- Data for Name: tipo_documento; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2411 (class 0 OID 0)
-- Dependencies: 195
-- Name: tipo_documento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_documento_id_seq', 1, false);


--
-- TOC entry 2346 (class 0 OID 34958)
-- Dependencies: 224
-- Data for Name: tipo_insumo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2412 (class 0 OID 0)
-- Dependencies: 196
-- Name: tipo_insumo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('tipo_insumo_id_seq', 1, false);


--
-- TOC entry 2347 (class 0 OID 34964)
-- Dependencies: 225
-- Data for Name: trabajador; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2413 (class 0 OID 0)
-- Dependencies: 197
-- Name: trabajador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('trabajador_id_seq', 1, false);


--
-- TOC entry 2348 (class 0 OID 34970)
-- Dependencies: 226
-- Data for Name: turno; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2414 (class 0 OID 0)
-- Dependencies: 198
-- Name: turno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('turno_id_seq', 1, false);


--
-- TOC entry 2349 (class 0 OID 34976)
-- Dependencies: 227
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario (id, user_name, password, actived, last_login_at, created_at, updated_at, deleted_at) VALUES (1, 'admin', '202cb962ac59075b964b07152d234b70', true, '2015-04-21 20:16:26', '2015-04-20 12:28:22.287', '2015-04-20 12:28:22.287', NULL);


--
-- TOC entry 2350 (class 0 OID 34989)
-- Dependencies: 228
-- Data for Name: usuario_credencial; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO usuario_credencial (id, usuario_id, credencial_id, created_at) VALUES (1, 1, 1, '2015-04-20 12:28:22.287');


--
-- TOC entry 2415 (class 0 OID 0)
-- Dependencies: 199
-- Name: usuario_credencial_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_credencial_id_seq', 1, true);


--
-- TOC entry 2416 (class 0 OID 0)
-- Dependencies: 200
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('usuario_id_seq', 1, true);


--
-- TOC entry 2105 (class 2606 OID 34882)
-- Name: pkanimal; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY hoja_de_vida
    ADD CONSTRAINT pkanimal PRIMARY KEY (id);


--
-- TOC entry 2085 (class 2606 OID 34818)
-- Name: pkbitacora; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT pkbitacora PRIMARY KEY (id);


--
-- TOC entry 2087 (class 2606 OID 34826)
-- Name: pkciudad; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY ciudad
    ADD CONSTRAINT pkciudad PRIMARY KEY (id);


--
-- TOC entry 2089 (class 2606 OID 34834)
-- Name: pkcredencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY credencial
    ADD CONSTRAINT pkcredencial PRIMARY KEY (id);


--
-- TOC entry 2091 (class 2606 OID 34840)
-- Name: pkdetalle_entrada_bodega; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_entrada_bodega
    ADD CONSTRAINT pkdetalle_entrada_bodega PRIMARY KEY (id);


--
-- TOC entry 2093 (class 2606 OID 34846)
-- Name: pkdetalle_pago_trabajador; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT pkdetalle_pago_trabajador PRIMARY KEY (id);


--
-- TOC entry 2095 (class 2606 OID 34852)
-- Name: pkdetalle_registro_vacunacion; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_registro_vacunacion
    ADD CONSTRAINT pkdetalle_registro_vacunacion PRIMARY KEY (id);


--
-- TOC entry 2097 (class 2606 OID 34858)
-- Name: pkdetalle_salida; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY detalle_salida
    ADD CONSTRAINT pkdetalle_salida PRIMARY KEY (id);


--
-- TOC entry 2099 (class 2606 OID 34864)
-- Name: pkentrada_bodega; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT pkentrada_bodega PRIMARY KEY (id);


--
-- TOC entry 2101 (class 2606 OID 34870)
-- Name: pkestado; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY estado
    ADD CONSTRAINT pkestado PRIMARY KEY (id);


--
-- TOC entry 2103 (class 2606 OID 34876)
-- Name: pkfecundador; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY fecundador
    ADD CONSTRAINT pkfecundador PRIMARY KEY (id);


--
-- TOC entry 2107 (class 2606 OID 34888)
-- Name: pkinsumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT pkinsumo PRIMARY KEY (id);


--
-- TOC entry 2109 (class 2606 OID 34894)
-- Name: pkinventario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT pkinventario PRIMARY KEY (id);


--
-- TOC entry 2111 (class 2606 OID 34900)
-- Name: pkordeno; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY ordeno
    ADD CONSTRAINT pkordeno PRIMARY KEY (id);


--
-- TOC entry 2113 (class 2606 OID 34906)
-- Name: pkpago_trabajadores; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY pago_trabajadores
    ADD CONSTRAINT pkpago_trabajadores PRIMARY KEY (id);


--
-- TOC entry 2115 (class 2606 OID 34912)
-- Name: pkprovedor; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT pkprovedor PRIMARY KEY (id);


--
-- TOC entry 2117 (class 2606 OID 34918)
-- Name: pkraza; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY raza
    ADD CONSTRAINT pkraza PRIMARY KEY (id);


--
-- TOC entry 2119 (class 2606 OID 34925)
-- Name: pkrecordar_me; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT pkrecordar_me PRIMARY KEY (id);


--
-- TOC entry 2123 (class 2606 OID 34933)
-- Name: pkregistro_celo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY registro_celo
    ADD CONSTRAINT pkregistro_celo PRIMARY KEY (id);


--
-- TOC entry 2125 (class 2606 OID 34939)
-- Name: pkregistro_vacunacion; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY registro_vacunacion
    ADD CONSTRAINT pkregistro_vacunacion PRIMARY KEY (id);


--
-- TOC entry 2127 (class 2606 OID 34945)
-- Name: pkreporte_parto; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY reporte_parto
    ADD CONSTRAINT pkreporte_parto PRIMARY KEY (id);


--
-- TOC entry 2129 (class 2606 OID 34951)
-- Name: pksalida_bodega; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY salida_bodega
    ADD CONSTRAINT pksalida_bodega PRIMARY KEY (id);


--
-- TOC entry 2131 (class 2606 OID 34957)
-- Name: pktipo_documento; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_documento
    ADD CONSTRAINT pktipo_documento PRIMARY KEY (id);


--
-- TOC entry 2133 (class 2606 OID 34963)
-- Name: pktipo_insumo; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY tipo_insumo
    ADD CONSTRAINT pktipo_insumo PRIMARY KEY (id);


--
-- TOC entry 2135 (class 2606 OID 34969)
-- Name: pktrabajador; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY trabajador
    ADD CONSTRAINT pktrabajador PRIMARY KEY (id);


--
-- TOC entry 2137 (class 2606 OID 34975)
-- Name: pkturno; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY turno
    ADD CONSTRAINT pkturno PRIMARY KEY (id);


--
-- TOC entry 2139 (class 2606 OID 34984)
-- Name: pkusuario; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario
    ADD CONSTRAINT pkusuario PRIMARY KEY (id);


--
-- TOC entry 2145 (class 2606 OID 34995)
-- Name: pkusuario_credencial; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT pkusuario_credencial PRIMARY KEY (id);


--
-- TOC entry 2082 (class 1259 OID 34819)
-- Name: bitacora_fecha_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_fecha_Idx" ON bitacora USING btree (fecha);


--
-- TOC entry 2083 (class 1259 OID 34820)
-- Name: bitacora_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora USING btree (usuario_id);


--
-- TOC entry 2120 (class 1259 OID 34926)
-- Name: recordar_me_ip_address_hash_cookie_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me USING btree (ip_address, hash_cookie);


--
-- TOC entry 2121 (class 1259 OID 34927)
-- Name: recordar_me_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me USING btree (usuario_id);


--
-- TOC entry 2140 (class 1259 OID 34985)
-- Name: usuario_actived_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_actived_Idx" ON usuario USING btree (actived);


--
-- TOC entry 2146 (class 1259 OID 34996)
-- Name: usuario_credencial_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial USING btree (credencial_id);


--
-- TOC entry 2147 (class 1259 OID 34997)
-- Name: usuario_credencial_usuario_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial USING btree (usuario_id);


--
-- TOC entry 2148 (class 1259 OID 34998)
-- Name: usuario_credencial_usuario_id_credencial_id_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial USING btree (usuario_id, credencial_id);


--
-- TOC entry 2141 (class 1259 OID 34986)
-- Name: usuario_deleted_at_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_deleted_at_Idx" ON usuario USING btree (deleted_at);


--
-- TOC entry 2142 (class 1259 OID 34987)
-- Name: usuario_user_name_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario USING btree (user_name);


--
-- TOC entry 2143 (class 1259 OID 34988)
-- Name: usuario_user_name_password_Idx; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX "usuario_user_name_password_Idx" ON usuario USING btree (user_name, password);


--
-- TOC entry 2163 (class 2606 OID 35069)
-- Name: fk_animal_estado; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY hoja_de_vida
    ADD CONSTRAINT fk_animal_estado FOREIGN KEY (id_estado) REFERENCES estado(id);


--
-- TOC entry 2164 (class 2606 OID 35074)
-- Name: fk_animal_raza; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY hoja_de_vida
    ADD CONSTRAINT fk_animal_raza FOREIGN KEY (id_raza) REFERENCES raza(id);


--
-- TOC entry 2149 (class 2606 OID 34999)
-- Name: fk_bitacora_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bitacora
    ADD CONSTRAINT fk_bitacora_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2150 (class 2606 OID 35004)
-- Name: fk_detalle_entrada_bodega_entrada_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_entrada_bodega
    ADD CONSTRAINT fk_detalle_entrada_bodega_entrada_bodega FOREIGN KEY (id_entrada_bodega) REFERENCES entrada_bodega(id);


--
-- TOC entry 2151 (class 2606 OID 35009)
-- Name: fk_detalle_entrada_bodega_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_entrada_bodega
    ADD CONSTRAINT fk_detalle_entrada_bodega_insumo FOREIGN KEY (id_insumo) REFERENCES insumo(id);


--
-- TOC entry 2153 (class 2606 OID 35019)
-- Name: fk_detalle_registro_vacunacion_animal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_registro_vacunacion
    ADD CONSTRAINT fk_detalle_registro_vacunacion_animal FOREIGN KEY (id_animal) REFERENCES hoja_de_vida(id);


--
-- TOC entry 2154 (class 2606 OID 35024)
-- Name: fk_detalle_registro_vacunacion_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_registro_vacunacion
    ADD CONSTRAINT fk_detalle_registro_vacunacion_insumo FOREIGN KEY (id_insumo) REFERENCES insumo(id);


--
-- TOC entry 2155 (class 2606 OID 35029)
-- Name: fk_detalle_registro_vacunacion_registro_vacunacion; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_registro_vacunacion
    ADD CONSTRAINT fk_detalle_registro_vacunacion_registro_vacunacion FOREIGN KEY (id_registro_vacunacion) REFERENCES registro_vacunacion(id);


--
-- TOC entry 2156 (class 2606 OID 35034)
-- Name: fk_detalle_salida_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_salida
    ADD CONSTRAINT fk_detalle_salida_insumo FOREIGN KEY (id_insumo) REFERENCES insumo(id);


--
-- TOC entry 2157 (class 2606 OID 35039)
-- Name: fk_detalle_salida_salida_bodega; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_salida
    ADD CONSTRAINT fk_detalle_salida_salida_bodega FOREIGN KEY (id_salida_bodega) REFERENCES salida_bodega(id);


--
-- TOC entry 2158 (class 2606 OID 35044)
-- Name: fk_detalle_salida_tipo_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_salida
    ADD CONSTRAINT fk_detalle_salida_tipo_insumo FOREIGN KEY (id_tipo_insumo) REFERENCES tipo_insumo(id);


--
-- TOC entry 2159 (class 2606 OID 35049)
-- Name: fk_entrada_bodega_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT fk_entrada_bodega_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedor(id);


--
-- TOC entry 2160 (class 2606 OID 35054)
-- Name: fk_entrada_bodega_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT fk_entrada_bodega_tipo_documento FOREIGN KEY (id_tipo_doc) REFERENCES tipo_documento(id);


--
-- TOC entry 2161 (class 2606 OID 35059)
-- Name: fk_entrada_bodega_trabajador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY entrada_bodega
    ADD CONSTRAINT fk_entrada_bodega_trabajador FOREIGN KEY (id_trabajador) REFERENCES trabajador(id);


--
-- TOC entry 2162 (class 2606 OID 35064)
-- Name: fk_fecundador_raza; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY fecundador
    ADD CONSTRAINT fk_fecundador_raza FOREIGN KEY (id_raza) REFERENCES raza(id);


--
-- TOC entry 2165 (class 2606 OID 35079)
-- Name: fk_insumo_tipo_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY insumo
    ADD CONSTRAINT fk_insumo_tipo_insumo FOREIGN KEY (id_tipo_insumo) REFERENCES tipo_insumo(id);


--
-- TOC entry 2166 (class 2606 OID 35084)
-- Name: fk_inventario_animal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_animal FOREIGN KEY (id_animal) REFERENCES hoja_de_vida(id);


--
-- TOC entry 2167 (class 2606 OID 35089)
-- Name: fk_inventario_insumo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT fk_inventario_insumo FOREIGN KEY (id_insumo) REFERENCES insumo(id);


--
-- TOC entry 2169 (class 2606 OID 35099)
-- Name: fk_ordeno_animal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY ordeno
    ADD CONSTRAINT fk_ordeno_animal FOREIGN KEY (id_animal) REFERENCES hoja_de_vida(id);


--
-- TOC entry 2170 (class 2606 OID 35104)
-- Name: fk_ordeno_trabajador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY ordeno
    ADD CONSTRAINT fk_ordeno_trabajador FOREIGN KEY (id_trabajador) REFERENCES trabajador(id);


--
-- TOC entry 2171 (class 2606 OID 35109)
-- Name: fk_pago_trabajadores_trabajador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY pago_trabajadores
    ADD CONSTRAINT fk_pago_trabajadores_trabajador FOREIGN KEY (id_trabajador) REFERENCES trabajador(id);


--
-- TOC entry 2172 (class 2606 OID 35114)
-- Name: fk_provedor_ciudad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY proveedor
    ADD CONSTRAINT fk_provedor_ciudad FOREIGN KEY (id_ciudad) REFERENCES ciudad(id);


--
-- TOC entry 2173 (class 2606 OID 35119)
-- Name: fk_recordar_me_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY recordar_me
    ADD CONSTRAINT fk_recordar_me_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2174 (class 2606 OID 35124)
-- Name: fk_registro_celo_animal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY registro_celo
    ADD CONSTRAINT fk_registro_celo_animal FOREIGN KEY (id_animal) REFERENCES hoja_de_vida(id);


--
-- TOC entry 2175 (class 2606 OID 35129)
-- Name: fk_registro_celo_fecundador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY registro_celo
    ADD CONSTRAINT fk_registro_celo_fecundador FOREIGN KEY (id_fecundador) REFERENCES fecundador(id);


--
-- TOC entry 2176 (class 2606 OID 35134)
-- Name: fk_registro_vacunacion_trabajador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY registro_vacunacion
    ADD CONSTRAINT fk_registro_vacunacion_trabajador FOREIGN KEY (id_trabajador) REFERENCES trabajador(id);


--
-- TOC entry 2177 (class 2606 OID 35139)
-- Name: fk_reporte_parto_animal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY reporte_parto
    ADD CONSTRAINT fk_reporte_parto_animal FOREIGN KEY (id_animal) REFERENCES hoja_de_vida(id);


--
-- TOC entry 2178 (class 2606 OID 35144)
-- Name: fk_salida_bodega_tipo_documento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY salida_bodega
    ADD CONSTRAINT fk_salida_bodega_tipo_documento FOREIGN KEY (id_tipo_doc) REFERENCES tipo_documento(id);


--
-- TOC entry 2179 (class 2606 OID 35149)
-- Name: fk_salida_bodega_trabajador; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY salida_bodega
    ADD CONSTRAINT fk_salida_bodega_trabajador FOREIGN KEY (id_trabajador) REFERENCES trabajador(id);


--
-- TOC entry 2180 (class 2606 OID 35154)
-- Name: fk_trabajador_ciudad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY trabajador
    ADD CONSTRAINT fk_trabajador_ciudad FOREIGN KEY (id_ciudad) REFERENCES ciudad(id);


--
-- TOC entry 2181 (class 2606 OID 35159)
-- Name: fk_trabajador_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY trabajador
    ADD CONSTRAINT fk_trabajador_credencial FOREIGN KEY (id_credencial) REFERENCES credencial(id);


--
-- TOC entry 2182 (class 2606 OID 35164)
-- Name: fk_trabajador_turno; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY trabajador
    ADD CONSTRAINT fk_trabajador_turno FOREIGN KEY (id_turno) REFERENCES turno(id);


--
-- TOC entry 2183 (class 2606 OID 35169)
-- Name: fk_usuario_credencial_credencial; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_credencial FOREIGN KEY (credencial_id) REFERENCES credencial(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2184 (class 2606 OID 35174)
-- Name: fk_usuario_credencial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY usuario_credencial
    ADD CONSTRAINT fk_usuario_credencial_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 2152 (class 2606 OID 35014)
-- Name: id_pago_trabajadores; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY detalle_pago_trabajadores
    ADD CONSTRAINT id_pago_trabajadores FOREIGN KEY (id_pago_trabajador) REFERENCES pago_trabajadores(id);


--
-- TOC entry 2168 (class 2606 OID 35094)
-- Name: id_tipo_doc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY inventario
    ADD CONSTRAINT id_tipo_doc FOREIGN KEY (id_tipo_doc) REFERENCES tipo_documento(id);


--
-- TOC entry 2356 (class 0 OID 0)
-- Dependencies: 5
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2015-04-21 13:33:36

--
-- PostgreSQL database dump complete
--


